### ISSUE TITLE
Status of sudbury

### ISSUE THREAD

**Issue by ThomasDuPlessis** [abooij/sudbury#13]
I was looking to make a window manager in Haskell for Wayland. Is Sudbury at a stage that it would be good for being used in such a project? I can't seem to find any documentation anywhere that would be useful for using the project.

**Comment by abooij** [comment]
I wouldn't say so. For server-side applications, the only thing sudbury offers is encoding and decoding byte streams into appropriate wayland packets. But I think much more than this can be done: the packets should automatically get relevant protocol metadata attached, and we should support a strongly typed callback mechanism (in which wayland packets of a certain type are processed by appropriate callbacks).

**Comment by ThomasDuPlessis** [comment]
Ohh ok I see. Would Hayland be better to use? Does it provide anymore functionality then this project?

**Comment by abooij** [comment]
I don't believe [hayland](https://github.com/abooij/haskell-wayland) is a useful direction of development: it doesn't allow access to the wayland protocol, it doesn't present utilities for writing window managers (but maybe one could write libweston bindings), it doesn't present a nice API for graphical programs, it doesn't present a nice API for debuggers.
